print("---------------ABC FOOD CITY-----------------")
print("=============================================")
print("")
print("               Good Morning                  ")
print("")
print("=============================================")
print(" ")
x=int(input("Enter first item price :  "))
y=int(input("Enter second item price:  "))
z=int(input("Enter third item price :  "))
a=int(input("Enter forth item price :  "))
b=int(input("Enter fifth item price :  "))
print("=============================================")
total=x+y+z+a+b
print(total)
a=int(input("Enter customer Amount:  "))
print("Balance:",a - total)
print("Thank you!")
print("come again!")
